title: Urbaine Public Relations & Corporate Communication Consulting
email: "hello@urbaine.au"
phone: "0418 748 892 or 0420 696 937"
description: "Urbaine is the property industry's specialist communication. We understand what it takes to bring a development's vision to life. consultancy."
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://urbaine.netlify.app" # the base hostname & protocol for your site, e.g. http://example.com


# Permalinks
permalink: pretty
permalink: /articles/:title/

include:
  - _pages
  - _redirects
  
# Build settings
plugins:
  - jekyll-feed

# Exclude from processing.
#
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - gulpfile.js
  - assets/scss
  - vendor
  - css